project:
  type: book
  output-dir: _book

book:
  title: "Hemlock Surgical Support Platform"
  subtitle: "Software Manual for Clinical Practice"
  author: 
    - name: "[Your Name/Organization]"
      affiliation: "[Your Institution]"
  date: "2025-08-14"
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: "Getting Started"
      chapters:
        - 01-platform-overview.qmd
        - 02-getting-started.qmd
        - 03-privacy-compliance.qmd
    
    - part: "Clinical Workflows"  
      chapters:
        - 04-patient-management.qmd
        - 05-clinical-data.qmd
        - 06-patient-treatment-outcomes.qmd
    
    - part: "Analytics & Optimization"
      chapters:
        - 07-reporting-analytics.qmd
        - 08-workflow-integration.qmd
    
    - part: "Support & Advanced Topics"
      chapters:
        - 09-troubleshooting.qmd
        - 10-development.qmd
        - appendices.qmd
    
    - references.qmd

  appendices:
    - appendices.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    cover-image: cover.png
    favicon: favicon.ico
    search: true
    repo-url: https://github.com/[your-repo]/hemlock-manual
    repo-actions: [edit, issue]
    
  pdf:
    documentclass: scrbook
    keep-tex: true

execute:
  freeze: auto
  cache: true

bibliography: references.bib
#csl: vancouver.csl  # Medical citation style

